import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import LogoTicker from "@/components/LogoTicker";
import ServicesCarousel from "@/components/ServicesCarousel";
import WhyChooseUs from "@/components/WhyChooseUs";
import CaseStudies from "@/components/CaseStudies";
import Testimonials from "@/components/Testimonials";
import { Blog, CommunityBanner } from "@/components/BlogAndCTA";
import Footer from "@/components/Footer";
import { FAQ, SectionCenteredLabel, SectionHeading, SectionLabel } from "@/components/services/ServiceComponents";

export default function Home() {
  return (
    <main>
      <Navbar />
      <Hero />
      <LogoTicker />
      <ServicesCarousel />
      <WhyChooseUs />
      <CaseStudies />
      <Testimonials />
      <Blog />
      <CommunityBanner />
      {/* FAQ */}
            <section style={{ background: "var(--color-bg-soft)", padding: "80px 24px" }}>
              <div style={{ maxWidth: 800, margin: "0 auto" }}>
                <div style={{ textAlign: "center", marginBottom: 48 }}>
                  <SectionCenteredLabel text="FAQ" />
                  <SectionHeading>Shoman solutions questions answered</SectionHeading>
                </div>
                <FAQ items={[
                  { q: "Is this an automated scan or a real expert review?", a: "It's a real expert review. Every audit is written by a senior engineer who actually reads your code, checks your configuration, and writes specific findings — not a report generated by a tool like Screaming Frog or GTmetrix. You can tell the difference immediately." },
                  { q: "What access do you need from us?", a: "For the Security & Core Health audit and Checkout audits, we need read-only admin access to your platform and ideally codebase access (Git or SFTP). For the Migration Complexity audit, we need admin access and ideally a database dump." },
                  { q: "What happens after the audit?", a: "You receive the report, we schedule a 30-minute review call to walk through the top findings, and you're free to implement with your own team or ask us to handle the remediation work. There's no pressure to engage further." },
                  { q: "Can the audit findings be fixed by our own developer?", a: "Yes — that's part of the value. The remediation guidance is written specifically so that any competent Magento or Shopify developer can pick it up and implement it, even if they didn't write the code originally." },
                ]} />
              </div>
            </section>
      <Footer />
    </main>
  );
}
